name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install twython
    - name: Create auth file
      run: |
        echo "API_KEY=1" >> auth.py
        echo "API_SECRET_KEY=1" >> auth.py
        echo "ACCESS_TOKEN=1" >> auth.py
        echo "ACCESS_TOKEN_SECRET=1" >> auth.py
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
