name: Send Tweet

on: # Run once every hour and on push
  schedule:
    - cron: '0 17 * * *'
  push:

jobs:
  tweet:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create auth file
      run: |
        printf "'''auth module'''\n" >> auth.py
        printf "$AUTH" >> auth.py
        printf "\n" >> auth.py
      shell: bash
      env:
        AUTH: ${{ secrets.AUTH }}
    - name: Send tweet
      run: |
        python beatles_lyrics_bot.py
