name: Send Tweet

on: # Run once every hour and on push
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - master

jobs:
  tweet:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create auth file
      run: |
        printf "'''auth module'''\n" >> auth.py
        printf "$AUTH" >> auth.py
        printf "\n" >> auth.py
      shell: bash
      env:
        AUTH: ${{ secrets.AUTH }}
    - name: Create Mastodon auth file
      run: |
        printf "'''auth module for Mastodon'''\n" >> masto_auth.py
        printf "$MASTO_AUTH" >> masto_auth.py
        printf "\n" >> masto_auth.py
      shell: bash
      env:
        MASTO_AUTH: ${{ secrets.MASTO_AUTH }}
    - name: Send tweet
      run: |
        python beatles_lyrics_bot.py
