name: Update repository

on: # Run once every hour and on push
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create dummy file
        run: date +%s > dummy
      - name: Commit dummy
        run: |
          git config --global user.name 'Jesús Jiménez Sánchez'
          git config --global user.email 'jesusjimsa@icloud.com'
          git add dummy
          git commit -am "Dummy commit for Actions"
          git push
